[build]
    command = "npm run build"
    publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; img-src res.cloudinary.com; script-src googletagmanager.com"